### ISSUE TITLE
Errors with the script

### ISSUE THREAD

**Issue by TgamesFR** [thegreatunclean/uasset-dt-to-json#1]
Hi i got an error with the uasset-dt-to-json

D:\toto\uasset-dt-to-json-master>datatable-to-json.py Base_Counselor.uasset
Traceback (most recent call last):
  File "D:\toto\uasset-dt-to-json-master\datatable-to-json.py", line 758, in <module>
    uasset = UAsset(args.filename)
  File "D:\toto\uasset-dt-to-json-master\datatable-to-json.py", line 551, in __init__
    export.Object = UObject(stream, doPad=True, extra=export)
  File "D:\toto\uasset-dt-to-json-master\datatable-to-json.py", line 564, in __init__
    if (temp.value().CasePreservingHash.value() == 0xDC5):
  File "D:\toto\uasset-dt-to-json-master\datatable-to-json.py", line 234, in value
    return SummaryNames[self.Index.value()]
  File "D:\toto\uasset-dt-to-json-master\datatable-to-json.py", line 65, in value
    return struct.unpack("q", self.raw)[0]
struct.error: unpack requires a buffer of 8 bytes

**Using theses files :**

[UassetExampleFile.zip](https://github.com/thegreatunclean/uasset-dt-to-json/files/3531022/UassetExampleFile.zip)

**Comment by TgamesFR** [comment]
Here is also more example of Uasset and Uexp files who doesn't works on uasset-dt-to-json.
[MoreUassetExamplesFiles.zip](https://github.com/thegreatunclean/uasset-dt-to-json/files/3531055/MoreUassetExamplesFiles.zip)

**Comment by antoshre** [comment]
The symptom is the parser is trying to read some bytes past the end of the file, causing `struct` to throw an exception.  The cause is the parser not correctly decoding the 6th `FObjectExport` tag after (presumably) correctly parsing the first five and I have no idea why.  That tag holds the offset where it tries to read the export data from so when that gets corrupted the whole thing goes down in flames.
It even crashes the UAsset2Json parser that I've based my code on.  That's something I haven't seen before.
I'll try and walk `Base_Counselor.uasset` through by hand to see if it's a bug in my implementation or some crazy uasset "feature" I've never seen.

**Comment by TgamesFR** [comment]
Thanks for your fast answer.
My goal is the understand or get where are the float values in the uexp for each referenced elements in the uasset file. Without that it's a long and very hard search with hxD haha xD (hours just for one single value...LOL). 

About theses Uasset files, someone has made a private tool who perfectly export everything in multiples json files (Base_Counselor.uasset.ExportSummary.json, Base_Counselor.uasset.ImportSummary.json, Base_Counselor.uasset.NameSummary.json, Base_Counselor.uasset.ObjectSummary.json and Base_Counselor.uasset.PackageSummary.json)

You can download the full export in Json of the Uasset example file i send to you on post #1 here :
[ExportInJSON.zip](https://github.com/thegreatunclean/uasset-dt-to-json/files/3532425/ExportInJSON.zip)

With this export in json it's so easy to mod values in the uexp. **But the software is private**, i just got this JSON export he made on single uasset file (and i'm not able to get more export in Json of theses uasset files). And the person doesn't want to share his software :/

It will be so great if you can add the support of theses UASSET file in your program. I'm really really need a program to export theses uasset in json format. It will save me hours and days of searching values manually... xD.
Thanks !
Best Regards.

**Comment by antoshre** [comment]
Man do I hate this file format.  But I have an update:

Turns out I've been parsing `FObjectExport` incorrectly.  All my test files so far have had 1 export tag, this file has 238.  The JSON dump doesn't list a 32-bit field I'm currently decoding blindly, once I removed that field all 238 decode fine and match the JSON dump you provided.
The first export has an offset of `68069`, which happens to be the precise end of the `.uasset` file.  The `.uexp` file looks like it contains valid tags starting at offset=`0`.  All further export offsets are beyond the end of the file.  I suspect any access after the end of the `.uasset` is meant to be redirected to the `.uexp`.  Haven't seen that before.

I'll add it a hack that tries to handle this case within the next few days.  It won't be pretty but it should at least allow me to test whether my assumption is correct.  If it works I'll push it to a different branch to prep for integration into the re-write I've already got in the works.

**Comment by TgamesFR** [comment]
Thanks a lot for your hard work @thegreatunclean !
And sorry for my strange uasset files lol ^^
Perfect ! Tell me if you need more uasset files to test and if i need to test something to help you.

And again thanks for your answers and your hard work on theses uasset files :).
Best Regards !

**Comment by TgamesFR** [comment]
Hi @thegreatunclean, do you have a temporarily code i can use to get some offsets (FObjectExport) of my uasset files ? Thanks :).

**Comment by antoshre** [comment]
[This commit](https://github.com/thegreatunclean/uasset-dt-to-json/tree/1988ae9a221b9d4fb736aa7a45dd2a1f6b8575fe) makes it "parse" but there are large chunks that I don't know how to decode.  Parsing only proceeds by blind-reading in chunks of data the tag specifies, and the JSON printer doesn't handle the structure anyhow.
Without some solid reference to go on I'm not sure what more I can do.  The information is probably buried in the structure but you'd have to re-write the JSON dumping to extract it.

**Comment by TgamesFR** [comment]
Thanks, yes i can only get the names but no offsets in the export :/
