### ISSUE TITLE
struct.error: unpack requires a buffer of 8 bytes

### ISSUE THREAD

**Issue by xMistt** [thegreatunclean/uasset-dt-to-json#2]
When trying to convert a .uasset file I get this error:
```
Traceback (most recent call last):
  File "dumper.py", line 758, in <module>
    uasset = UAsset(args.filename)
  File "dumper.py", line 551, in __init__
    export.Object = UObject(stream, doPad=True, extra=export)
  File "dumper.py", line 564, in __init__
    if (temp.value().CasePreservingHash.value() == 0xDC5):
  File "dumper.py", line 234, in value
    return SummaryNames[self.Index.value()]
  File "dumper.py", line 65, in value
    return struct.unpack("q", self.raw)[0]
struct.error: unpack requires a buffer of 8 bytes
```

**Comment by xMistt** [comment]
Still happening.
